# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
  
    name: Julia ${{ matrix.version }} - ${{ matrix.tests }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      test_suite:  ${{ matrix.tests }}

    strategy:
      fail-fast: false

      matrix:
        version: ['1.5', '1.6']
        tests: ["basics", "layers", "networks"]
        os: [ubuntu-latest]


    steps:
      - name: Checkout AzureClusterlessHPC.jl
        uses: actions/checkout@v2

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          
      - name: Build AzureClusterlessHPC.jl
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest
